function fourierBasis = stateLift(in1)
%STATELIFT
%    FOURIERBASIS = STATELIFT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    24-Oct-2018 12:28:52

ud1 = in1(17,:);
ud2 = in1(18,:);
ud3 = in1(19,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
xd1 = in1(5,:);
xd2 = in1(6,:);
xd3 = in1(7,:);
xd4 = in1(8,:);
xd5 = in1(9,:);
xd6 = in1(10,:);
xd7 = in1(11,:);
xd8 = in1(12,:);
xd9 = in1(13,:);
xd10 = in1(14,:);
xd11 = in1(15,:);
xd12 = in1(16,:);
t2 = x1.*pi.*2.0;
t3 = x2.*pi.*2.0;
t4 = x3.*pi.*2.0;
t5 = x4.*pi.*2.0;
t6 = xd1.*pi.*2.0;
t7 = xd2.*pi.*2.0;
t8 = xd3.*pi.*2.0;
t9 = xd4.*pi.*2.0;
t10 = xd5.*pi.*2.0;
t11 = xd6.*pi.*2.0;
t12 = xd7.*pi.*2.0;
t13 = xd8.*pi.*2.0;
t14 = xd9.*pi.*2.0;
t15 = xd10.*pi.*2.0;
t16 = xd11.*pi.*2.0;
t17 = xd12.*pi.*2.0;
t18 = ud1.*pi.*2.0;
t19 = ud2.*pi.*2.0;
t20 = ud3.*pi.*2.0;
fourierBasis = [x1;x2;x3;x4;xd1;xd2;xd3;xd4;xd5;xd6;xd7;xd8;xd9;xd10;xd11;xd12;ud1;ud2;ud3;1.0;sin(t2);sin(t3);sin(t4);sin(t5);sin(t6);sin(t7);sin(t8);sin(t9);sin(t10);sin(t11);sin(t12);sin(t13);sin(t14);sin(t15);sin(t16);sin(t17);sin(t18);sin(t19);sin(t20);cos(t2);cos(t3);cos(t4);cos(t5);cos(t6);cos(t7);cos(t8);cos(t9);cos(t10);cos(t11);cos(t12);cos(t13);cos(t14);cos(t15);cos(t16);cos(t17);cos(t18);cos(t19);cos(t20)];
