function [f, dfdx, dfdu, df_ddxdt] = vf(x, u, dxdt, params)

    n = params.n;
    m = params.m;
    
    [c1, c2, c3] = deal(params.Felast_consts(1), params.Felast_consts(2), params.Felast_consts(3));
    [c4, c5, c6] = deal(params.Melast_consts(1), params.Melast_consts(2), params.Melast_consts(3));
    
    [P0, gama0, r0, L0] = deal(params.x_rest(1), params.x_rest(2), params.x_rest(3), params.x_rest(4));
    [P, gama, r, L] = deal(x(1), x(2), x(3), x(4));
    [dP, dgama, dr, dL] = deal(dxdt(1), dxdt(2), dxdt(3), dxdt(4));

%% Regular Version. Matches ICRA equations, only r moves in wrong direction (1/7/2017)    
%     f = [-dP + 0.5*(u - P);...  % The constant in front of (u-P) is arbitrary
%          c2*dL + 2*c1*L*dL + pi*r^2*dP + 2*pi*P*r*dr - 2*pi*cot(gama)^2*r^2*dP - 4*pi*cot(gama)^2*P*r*dr + 4*pi*cot(gama)*P*r^2*dgama*(cot(gama)^2 + 1);...
%          2*pi*P*r^3*dgama*(cot(gama)^2 + 1) - 2*c4*((L0*tan(gama0))/r0 - (tan(gama)*L)/r)*((tan(gama)*dL)/r + (L*(tan(gama)^2 + 1)*dgama)/r - (tan(gama)*L*dr)/r^2) - 2*pi*cot(gama)*r^3*dP - c5*((tan(gama)*dL)/r + (L*(tan(gama)^2 + 1)*dgama)/r - (tan(gama)*L*dr)/r^2) - 6*pi*cot(gama)*P*r^2*dr;...
%          sin(gama)*dgama + (cos(gama0)*dL)/L0];
%     
%     dfdx = [-1*0.5,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0,                                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                                                                                                                     0;...
%             2*pi*dr*r - 4*pi*dr*r*cot(gama)^2 + 4*pi*dgama*r^2*cot(gama)*(cot(gama)^2 + 1), 4*pi*dP*r^2*cot(gama)*(cot(gama)^2 + 1) - 4*pi*P*dgama*r^2*(cot(gama)^2 + 1)^2 + 8*pi*P*dr*r*cot(gama)*(cot(gama)^2 + 1) - 8*pi*P*dgama*r^2*cot(gama)^2*(cot(gama)^2 + 1), 2*pi*P*dr + 2*pi*dP*r - 4*pi*P*dr*cot(gama)^2 - 4*pi*dP*r*cot(gama)^2 + 8*pi*P*dgama*r*cot(gama)*(cot(gama)^2 + 1), 2*c1*dL;...
%             2*pi*dgama*r^3*(cot(gama)^2 + 1) - 6*pi*dr*r^2*cot(gama), 2*c4*((L*tan(gama))/r - (L0*tan(gama0))/r0)*((dL*(tan(gama)^2 + 1))/r - (L*dr*(tan(gama)^2 + 1))/r^2 + (2*L*dgama*tan(gama)*(tan(gama)^2 + 1))/r) - c5*((dL*(tan(gama)^2 + 1))/r - (L*dr*(tan(gama)^2 + 1))/r^2 + (2*L*dgama*tan(gama)*(tan(gama)^2 + 1))/r) + 2*pi*dP*r^3*(cot(gama)^2 + 1) + (2*L*c4*(tan(gama)^2 + 1)*((dL*tan(gama))/r + (L*dgama*(tan(gama)^2 + 1))/r - (L*dr*tan(gama))/r^2))/r + 6*pi*P*dr*r^2*(cot(gama)^2 + 1) - 4*pi*P*dgama*r^3*cot(gama)*(cot(gama)^2 + 1), c5*((dL*tan(gama))/r^2 + (L*dgama*(tan(gama)^2 + 1))/r^2 - (2*L*dr*tan(gama))/r^3) - 2*c4*((L*tan(gama))/r - (L0*tan(gama0))/r0)*((dL*tan(gama))/r^2 + (L*dgama*(tan(gama)^2 + 1))/r^2 - (2*L*dr*tan(gama))/r^3) - 6*pi*dP*r^2*cot(gama) - 12*pi*P*dr*r*cot(gama) + 6*pi*P*dgama*r^2*(cot(gama)^2 + 1) - (2*L*c4*tan(gama)*((dL*tan(gama))/r + (L*dgama*(tan(gama)^2 + 1))/r - (L*dr*tan(gama))/r^2))/r^2, 2*c4*((dgama*(tan(gama)^2 + 1))/r - (dr*tan(gama))/r^2)*((L*tan(gama))/r - (L0*tan(gama0))/r0) - c5*((dgama*(tan(gama)^2 + 1))/r - (dr*tan(gama))/r^2) + (2*c4*tan(gama)*((dL*tan(gama))/r + (L*dgama*(tan(gama)^2 + 1))/r - (L*dr*tan(gama))/r^2))/r;...
%             0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                        dgama*cos(gama),                                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                                                                                                                     0];
%    
%     dfdu = [1*0.5;...
%             0;...
%             0;...
%             0];
%         
%     df_ddxdt = [-1,                                                                                                                               0,                                                                                                           0,                                                                            0;...
%                 pi*r^2 - 2*pi*r^2*cot(gama)^2, 4*pi*P*r^2*cot(gama)*(cot(gama)^2 + 1), 2*pi*P*r - 4*pi*P*r*cot(gama)^2, c2 + 2*L*c1;...
%                 -2*pi*r^3*cot(gama), 2*pi*P*r^3*(cot(gama)^2 + 1) - (L*c5*(tan(gama)^2 + 1))/r + (2*L*c4*((L*tan(gama))/r - (L0*tan(gama0))/r0)*(tan(gama)^2 + 1))/r, (L*c5*tan(gama))/r^2 - 6*pi*P*r^2*cot(gama) - (2*L*c4*tan(gama)*((L*tan(gama))/r - (L0*tan(gama0))/r0))/r^2, (2*c4*tan(gama)*((L*tan(gama))/r - (L0*tan(gama0))/r0))/r - (c5*tan(gama))/r;...
%                 0,                                                                                                                       sin(gama),                                                                                                           0,                                                                cos(gama0)/L0]; 
%     
    
%% Regular Version, except phi was multiplied by -1 in original force balance equations    
%     f = [-dP + 0.5*(u - P);...  % The constant in front of (u-P) is arbitrary
%          c2*dL + 2*c1*L*dL + pi*r^2*dP + 2*pi*P*r*dr - 2*pi*cot(gama)^2*r^2*dP - 4*pi*cot(gama)^2*P*r*dr + 4*pi*cot(gama)*P*r^2*dgama*(cot(gama)^2 + 1);...
%          c5*((tan(gama)*dL)/r + (L*(tan(gama)^2 + 1)*dgama)/r - (tan(gama)*L*dr)/r^2) - 2*c4*((L0*tan(gama0))/r0 - (tan(gama)*L)/r)*((tan(gama)*dL)/r + (L*(tan(gama)^2 + 1)*dgama)/r - (tan(gama)*L*dr)/r^2) - 2*pi*cot(gama)*r^3*dP + 2*pi*P*r^3*dgama*(cot(gama)^2 + 1) - 6*pi*cot(gama)*P*r^2*dr;...
%          sin(gama)*dgama + (cos(gama0)*dL)/L0];     
%          
%     dfdx = [-1*0.5,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0,                                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                                                                                                                     0;...
%             2*pi*dr*r - 4*pi*dr*r*cot(gama)^2 + 4*pi*dgama*r^2*cot(gama)*(cot(gama)^2 + 1), 4*pi*dP*r^2*cot(gama)*(cot(gama)^2 + 1) - 4*pi*P*dgama*r^2*(cot(gama)^2 + 1)^2 + 8*pi*P*dr*r*cot(gama)*(cot(gama)^2 + 1) - 8*pi*P*dgama*r^2*cot(gama)^2*(cot(gama)^2 + 1), 2*pi*P*dr + 2*pi*dP*r - 4*pi*P*dr*cot(gama)^2 - 4*pi*dP*r*cot(gama)^2 + 8*pi*P*dgama*r*cot(gama)*(cot(gama)^2 + 1), 2*c1*dL;...
%             2*pi*dgama*r^3*(cot(gama)^2 + 1) - 6*pi*dr*r^2*cot(gama), c5*((dL*(tan(gama)^2 + 1))/r - (L*dr*(tan(gama)^2 + 1))/r^2 + (2*L*dgama*tan(gama)*(tan(gama)^2 + 1))/r) + 2*c4*((L*tan(gama))/r - (L0*tan(gama0))/r0)*((dL*(tan(gama)^2 + 1))/r - (L*dr*(tan(gama)^2 + 1))/r^2 + (2*L*dgama*tan(gama)*(tan(gama)^2 + 1))/r) + 2*pi*dP*r^3*(cot(gama)^2 + 1) + (2*L*c4*(tan(gama)^2 + 1)*((dL*tan(gama))/r + (L*dgama*(tan(gama)^2 + 1))/r - (L*dr*tan(gama))/r^2))/r + 6*pi*P*dr*r^2*(cot(gama)^2 + 1) - 4*pi*P*dgama*r^3*cot(gama)*(cot(gama)^2 + 1), 6*pi*P*dgama*r^2*(cot(gama)^2 + 1) - 2*c4*((L*tan(gama))/r - (L0*tan(gama0))/r0)*((dL*tan(gama))/r^2 + (L*dgama*(tan(gama)^2 + 1))/r^2 - (2*L*dr*tan(gama))/r^3) - 6*pi*dP*r^2*cot(gama) - 12*pi*P*dr*r*cot(gama) - c5*((dL*tan(gama))/r^2 + (L*dgama*(tan(gama)^2 + 1))/r^2 - (2*L*dr*tan(gama))/r^3) - (2*L*c4*tan(gama)*((dL*tan(gama))/r + (L*dgama*(tan(gama)^2 + 1))/r - (L*dr*tan(gama))/r^2))/r^2, c5*((dgama*(tan(gama)^2 + 1))/r - (dr*tan(gama))/r^2) + 2*c4*((dgama*(tan(gama)^2 + 1))/r - (dr*tan(gama))/r^2)*((L*tan(gama))/r - (L0*tan(gama0))/r0) + (2*c4*tan(gama)*((dL*tan(gama))/r + (L*dgama*(tan(gama)^2 + 1))/r - (L*dr*tan(gama))/r^2))/r;...
%             0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                        dgama*cos(gama),                                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                                                                                                                     0];
%    
%     dfdu = [1*0.5;...
%             0;...
%             0;...
%             0];
%         
%     df_ddxdt = [-1,                                                                                                                               0,                                                                                                           0,                                                                            0;...
%                 pi*r^2 - 2*pi*r^2*cot(gama)^2, 4*pi*P*r^2*cot(gama)*(cot(gama)^2 + 1), 2*pi*P*r - 4*pi*P*r*cot(gama)^2, c2 + 2*L*c1;...
%                 -2*pi*r^3*cot(gama), 2*pi*P*r^3*(cot(gama)^2 + 1) + (L*c5*(tan(gama)^2 + 1))/r + (2*L*c4*((L*tan(gama))/r - (L0*tan(gama0))/r0)*(tan(gama)^2 + 1))/r, - 6*pi*P*r^2*cot(gama) - (L*c5*tan(gama))/r^2 - (2*L*c4*tan(gama)*((L*tan(gama))/r - (L0*tan(gama0))/r0))/r^2, (c5*tan(gama))/r + (2*c4*tan(gama)*((L*tan(gama))/r - (L0*tan(gama0))/r0))/r;...
%                 0,                                                                                                                       sin(gama),                                                                                                           0,                                                                cos(gama0)/L0]; 
%  

%% Version where F_elast is a function of (L-L0)
%     f = [-dP + 0.5*(u - P);...  % The constant in front of (u-P) is arbitrary
%          c2*dL - 2*c1*dL*(L0 - L) + pi*r^2*dP + 2*pi*P*r*dr - 2*pi*cot(gama)^2*r^2*dP - 4*pi*cot(gama)^2*P*r*dr + 4*pi*cot(gama)*P*r^2*dgama*(cot(gama)^2 + 1);...
%          c5*((tan(gama)*dL)/r + (L*(tan(gama)^2 + 1)*dgama)/r - (tan(gama)*L*dr)/r^2) - 2*c4*((L0*tan(gama0))/r0 - (tan(gama)*L)/r)*((tan(gama)*dL)/r + (L*(tan(gama)^2 + 1)*dgama)/r - (tan(gama)*L*dr)/r^2) - 2*pi*cot(gama)*r^3*dP + 2*pi*P*r^3*dgama*(cot(gama)^2 + 1) - 6*pi*cot(gama)*P*r^2*dr;...
%          sin(gama)*dgama + (cos(gama0)*dL)/L0];     
%          
%     dfdx = [-1*0.5,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0,                                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                                                                                                                     0;...
%             2*pi*dr*r - 4*pi*dr*r*cot(gama)^2 + 4*pi*dgama*r^2*cot(gama)*(cot(gama)^2 + 1), 4*pi*dP*r^2*cot(gama)*(cot(gama)^2 + 1) - 4*pi*P*dgama*r^2*(cot(gama)^2 + 1)^2 + 8*pi*P*dr*r*cot(gama)*(cot(gama)^2 + 1) - 8*pi*P*dgama*r^2*cot(gama)^2*(cot(gama)^2 + 1), 2*pi*P*dr + 2*pi*dP*r - 4*pi*P*dr*cot(gama)^2 - 4*pi*dP*r*cot(gama)^2 + 8*pi*P*dgama*r*cot(gama)*(cot(gama)^2 + 1), 2*c1*dL;...
%             2*pi*dgama*r^3*(cot(gama)^2 + 1) - 6*pi*dr*r^2*cot(gama), c5*((dL*(tan(gama)^2 + 1))/r - (L*dr*(tan(gama)^2 + 1))/r^2 + (2*L*dgama*tan(gama)*(tan(gama)^2 + 1))/r) + 2*c4*((L*tan(gama))/r - (L0*tan(gama0))/r0)*((dL*(tan(gama)^2 + 1))/r - (L*dr*(tan(gama)^2 + 1))/r^2 + (2*L*dgama*tan(gama)*(tan(gama)^2 + 1))/r) + 2*pi*dP*r^3*(cot(gama)^2 + 1) + (2*L*c4*(tan(gama)^2 + 1)*((dL*tan(gama))/r + (L*dgama*(tan(gama)^2 + 1))/r - (L*dr*tan(gama))/r^2))/r + 6*pi*P*dr*r^2*(cot(gama)^2 + 1) - 4*pi*P*dgama*r^3*cot(gama)*(cot(gama)^2 + 1), 6*pi*P*dgama*r^2*(cot(gama)^2 + 1) - 2*c4*((L*tan(gama))/r - (L0*tan(gama0))/r0)*((dL*tan(gama))/r^2 + (L*dgama*(tan(gama)^2 + 1))/r^2 - (2*L*dr*tan(gama))/r^3) - 6*pi*dP*r^2*cot(gama) - 12*pi*P*dr*r*cot(gama) - c5*((dL*tan(gama))/r^2 + (L*dgama*(tan(gama)^2 + 1))/r^2 - (2*L*dr*tan(gama))/r^3) - (2*L*c4*tan(gama)*((dL*tan(gama))/r + (L*dgama*(tan(gama)^2 + 1))/r - (L*dr*tan(gama))/r^2))/r^2, c5*((dgama*(tan(gama)^2 + 1))/r - (dr*tan(gama))/r^2) + 2*c4*((dgama*(tan(gama)^2 + 1))/r - (dr*tan(gama))/r^2)*((L*tan(gama))/r - (L0*tan(gama0))/r0) + (2*c4*tan(gama)*((dL*tan(gama))/r + (L*dgama*(tan(gama)^2 + 1))/r - (L*dr*tan(gama))/r^2))/r;...
%             0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                        dgama*cos(gama),                                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                                                                                                                     0];
%    
%     dfdu = [1*0.5;...
%             0;...
%             0;...
%             0];
%         
%     df_ddxdt = [-1,                                                                                                                               0,                                                                                                           0,                                                                            0;...
%                 pi*r^2 - 2*pi*r^2*cot(gama)^2, 4*pi*P*r^2*cot(gama)*(cot(gama)^2 + 1), 2*pi*P*r - 4*pi*P*r*cot(gama)^2, c2 + 2*c1*(L - L0);...
%                 -2*pi*r^3*cot(gama), 2*pi*P*r^3*(cot(gama)^2 + 1) + (L*c5*(tan(gama)^2 + 1))/r + (2*L*c4*((L*tan(gama))/r - (L0*tan(gama0))/r0)*(tan(gama)^2 + 1))/r, - 6*pi*P*r^2*cot(gama) - (L*c5*tan(gama))/r^2 - (2*L*c4*tan(gama)*((L*tan(gama))/r - (L0*tan(gama0))/r0))/r^2, (c5*tan(gama))/r + (2*c4*tan(gama)*((L*tan(gama))/r - (L0*tan(gama0))/r0))/r;...
%                 0,                                                                                                                       sin(gama),                                                                                                           0,                                                                cos(gama0)/L0]; 
%         

%% Version where F_elast = (L-L0), M_elast = phi (1/10/2017)
%     f = [-dP + 0.5*(u - P);...  % The constant in front of (u-P) is arbitrary
%          dL + pi*r^2*dP + 2*pi*P*r*dr - 2*pi*cot(gama)^2*r^2*dP - 4*pi*cot(gama)^2*P*r*dr + 4*pi*cot(gama)*P*r^2*dgama*(cot(gama)^2 + 1);...
%          (tan(gama)*L*dr)/r^2 - (L*(tan(gama)^2 + 1)*dgama)/r - (tan(gama)*dL)/r - 2*pi*cot(gama)*r^3*dP + 2*pi*P*r^3*dgama*(cot(gama)^2 + 1) - 6*pi*cot(gama)*P*r^2*dr;...
%          sin(gama)*dgama + (cos(gama0)*dL)/L0];
%     
%     dfdx = [-1*0.5,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0,                                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                                                                                                                     0;...
%             2*pi*dr*r - 4*pi*dr*r*cot(gama)^2 + 4*pi*dgama*r^2*cot(gama)*(cot(gama)^2 + 1), 4*pi*dP*r^2*cot(gama)*(cot(gama)^2 + 1) - 4*pi*P*dgama*r^2*(cot(gama)^2 + 1)^2 + 8*pi*P*dr*r*cot(gama)*(cot(gama)^2 + 1) - 8*pi*P*dgama*r^2*cot(gama)^2*(cot(gama)^2 + 1), 2*pi*P*dr + 2*pi*dP*r - 4*pi*P*dr*cot(gama)^2 - 4*pi*dP*r*cot(gama)^2 + 8*pi*P*dgama*r*cot(gama)*(cot(gama)^2 + 1), 0;...
%             2*pi*dgama*r^3*(cot(gama)^2 + 1) - 6*pi*dr*r^2*cot(gama), 2*pi*dP*r^3*(cot(gama)^2 + 1) - (dL*(tan(gama)^2 + 1))/r + (L*dr*(tan(gama)^2 + 1))/r^2 - (2*L*dgama*tan(gama)*(tan(gama)^2 + 1))/r + 6*pi*P*dr*r^2*(cot(gama)^2 + 1) - 4*pi*P*dgama*r^3*cot(gama)*(cot(gama)^2 + 1), (dL*tan(gama))/r^2 + (L*dgama*(tan(gama)^2 + 1))/r^2 - 6*pi*dP*r^2*cot(gama) - (2*L*dr*tan(gama))/r^3 - 12*pi*P*dr*r*cot(gama) + 6*pi*P*dgama*r^2*(cot(gama)^2 + 1), (dr*tan(gama))/r^2 - (dgama*(tan(gama)^2 + 1))/r;...
%             0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                        dgama*cos(gama),                                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                                                                                                                     0];
%    
%     dfdu = [1*0.5;...
%             0;...
%             0;...
%             0];
%         
%     df_ddxdt = [-1,                                                                                                                               0,                                                                                                           0,                                                                            0;...
%                 pi*r^2 - 2*pi*r^2*cot(gama)^2, 4*pi*P*r^2*cot(gama)*(cot(gama)^2 + 1), 2*pi*P*r - 4*pi*P*r*cot(gama)^2, 1;...
%                 -2*pi*r^3*cot(gama), 2*pi*P*r^3*(cot(gama)^2 + 1) - (L*(tan(gama)^2 + 1))/r, (L*tan(gama))/r^2 - 6*pi*P*r^2*cot(gama), -tan(gama)/r;...
%                 0,                                                                                                                       sin(gama),                                                                                                           0,                                                                cos(gama0)/L0]; 
%     
%% Version where F_elast = M_elast = 0 (1/10/2017)
%     f = [-dP + 0.5*(u - P);...  % The constant in front of (u-P) is arbitrary
%          pi*r^2*dP + 2*pi*P*r*dr - 2*pi*cot(gama)^2*r^2*dP - 4*pi*cot(gama)^2*P*r*dr + 4*pi*cot(gama)*P*r^2*dgama*(cot(gama)^2 + 1);...
%          2*pi*P*r^3*dgama*(cot(gama)^2 + 1) - 2*pi*cot(gama)*r^3*dP - 6*pi*cot(gama)*P*r^2*dr;...
%          sin(gama)*dgama + (cos(gama0)*dL)/L0];
%     
%     dfdx = [-1*0.5,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0,                                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                                                                                                                     0;...
%             2*pi*dr*r - 4*pi*dr*r*cot(gama)^2 + 4*pi*dgama*r^2*cot(gama)*(cot(gama)^2 + 1), 4*pi*dP*r^2*cot(gama)*(cot(gama)^2 + 1) - 4*pi*P*dgama*r^2*(cot(gama)^2 + 1)^2 + 8*pi*P*dr*r*cot(gama)*(cot(gama)^2 + 1) - 8*pi*P*dgama*r^2*cot(gama)^2*(cot(gama)^2 + 1), 2*pi*P*dr + 2*pi*dP*r - 4*pi*P*dr*cot(gama)^2 - 4*pi*dP*r*cot(gama)^2 + 8*pi*P*dgama*r*cot(gama)*(cot(gama)^2 + 1), 0;...
%             2*pi*dgama*r^3*(cot(gama)^2 + 1) - 6*pi*dr*r^2*cot(gama), 2*pi*dP*r^3*(cot(gama)^2 + 1) + 6*pi*P*dr*r^2*(cot(gama)^2 + 1) - 4*pi*P*dgama*r^3*cot(gama)*(cot(gama)^2 + 1), 6*pi*P*dgama*r^2*(cot(gama)^2 + 1) - 12*pi*P*dr*r*cot(gama) - 6*pi*dP*r^2*cot(gama), 0;...
%             0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                        dgama*cos(gama),                                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                                                                                                                     0];
%    
%     dfdu = [1*0.5;...
%             0;...
%             0;...
%             0];
%         
%     df_ddxdt = [-1,                                                                                                                               0,                                                                                                           0,                                                                            0;...
%                 pi*r^2 - 2*pi*r^2*cot(gama)^2, 4*pi*P*r^2*cot(gama)*(cot(gama)^2 + 1), 2*pi*P*r - 4*pi*P*r*cot(gama)^2, 0;...
%                 -2*pi*r^3*cot(gama), 2*pi*P*r^3*(cot(gama)^2 + 1), -6*pi*P*r^2*cot(gama), 0;...
%                 0,                                                                                                                       sin(gama),                                                                                                           0,                                                                cos(gama0)/L0]; 
         
%% Version where F_elast = (L-L0), M_elast = theta (1/12/2017)
%     f = [-dP + 0.5*(u - P);...  % The constant in front of (u-P) is arbitrary
%          dL + pi*r^2*dP + 2*pi*P*r*dr - 2*pi*cot(gama)^2*r^2*dP - 4*pi*cot(gama)^2*P*r*dr + 4*pi*cot(gama)*P*r^2*dgama*(cot(gama)^2 + 1);...
%          (tan(gama)*dL)/r + (L*(tan(gama)^2 + 1)*dgama)/r - (tan(gama)*L*dr)/r^2 - 2*pi*cot(gama)*r^3*dP + 2*pi*P*r^3*dgama*(cot(gama)^2 + 1) - 6*pi*cot(gama)*P*r^2*dr;...
%          sin(gama)*dgama + (cos(gama0)*dL)/L0];
%     
%     dfdx = [-1*0.5,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0,                                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                                                                                                                     0;...
%             2*pi*dr*r - 4*pi*dr*r*cot(gama)^2 + 4*pi*dgama*r^2*cot(gama)*(cot(gama)^2 + 1), 4*pi*dP*r^2*cot(gama)*(cot(gama)^2 + 1) - 4*pi*P*dgama*r^2*(cot(gama)^2 + 1)^2 + 8*pi*P*dr*r*cot(gama)*(cot(gama)^2 + 1) - 8*pi*P*dgama*r^2*cot(gama)^2*(cot(gama)^2 + 1), 2*pi*P*dr + 2*pi*dP*r - 4*pi*P*dr*cot(gama)^2 - 4*pi*dP*r*cot(gama)^2 + 8*pi*P*dgama*r*cot(gama)*(cot(gama)^2 + 1), 0;...
%             2*pi*dgama*r^3*(cot(gama)^2 + 1) - 6*pi*dr*r^2*cot(gama), (dL*(tan(gama)^2 + 1))/r + 2*pi*dP*r^3*(cot(gama)^2 + 1) - (L*dr*(tan(gama)^2 + 1))/r^2 + (2*L*dgama*tan(gama)*(tan(gama)^2 + 1))/r + 6*pi*P*dr*r^2*(cot(gama)^2 + 1) - 4*pi*P*dgama*r^3*cot(gama)*(cot(gama)^2 + 1), (2*L*dr*tan(gama))/r^3 - (L*dgama*(tan(gama)^2 + 1))/r^2 - 6*pi*dP*r^2*cot(gama) - (dL*tan(gama))/r^2 - 12*pi*P*dr*r*cot(gama) + 6*pi*P*dgama*r^2*(cot(gama)^2 + 1), (dgama*(tan(gama)^2 + 1))/r - (dr*tan(gama))/r^2;...
%             0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                        dgama*cos(gama),                                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                                                                                                                     0];
%    
%     dfdu = [1*0.5;...
%             0;...
%             0;...
%             0];
%         
%     df_ddxdt = [-1,                                                                                                                               0,                                                                                                           0,                                                                            0;...
%                 pi*r^2 - 2*pi*r^2*cot(gama)^2, 4*pi*P*r^2*cot(gama)*(cot(gama)^2 + 1), 2*pi*P*r - 4*pi*P*r*cot(gama)^2, 1;...
%                 -2*pi*r^3*cot(gama), (L*(tan(gama)^2 + 1))/r + 2*pi*P*r^3*(cot(gama)^2 + 1), - (L*tan(gama))/r^2 - 6*pi*P*r^2*cot(gama), tan(gama)/r;...
%                 0,                                                                                                                       sin(gama),                                                                                                           0,                                                                cos(gama0)/L0]; 
%          

%% Version where F_elast = (L-L0)*(r/r0), M_elast = phi*(r/r0) (1/12/2017)
%     f = [-dP + 0.5*(u - P);...  % The constant in front of (u-P) is arbitrary
%          pi*r^2*dP + (r*dL)/r0 - (dr*(L0 - L))/r0 + 2*pi*P*r*dr - 2*pi*cot(gama)^2*r^2*dP - 4*pi*cot(gama)^2*P*r*dr + 4*pi*cot(gama)*P*r^2*dgama*(cot(gama)^2 + 1);...
%          (((L0*tan(gama0))/r0 - (tan(gama)*L)/r)*dr)/r0 - (r*((tan(gama)*dL)/r + (L*(tan(gama)^2 + 1)*dgama)/r - (tan(gama)*L*dr)/r^2))/r0 - 2*pi*cot(gama)*r^3*dP + 2*pi*P*r^3*dgama*(cot(gama)^2 + 1) - 6*pi*cot(gama)*P*r^2*dr;...
%          sin(gama)*dgama + (cos(gama0)*dL)/L0];
%     
%     dfdx = [-1*0.5,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0,                                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                                                                                                                     0;...
%             2*pi*dr*r - 4*pi*dr*r*cot(gama)^2 + 4*pi*dgama*r^2*cot(gama)*(cot(gama)^2 + 1), 4*pi*dP*r^2*cot(gama)*(cot(gama)^2 + 1) - 4*pi*P*dgama*r^2*(cot(gama)^2 + 1)^2 + 8*pi*P*dr*r*cot(gama)*(cot(gama)^2 + 1) - 8*pi*P*dgama*r^2*cot(gama)^2*(cot(gama)^2 + 1), dL/r0 + 2*pi*P*dr + 2*pi*dP*r - 4*pi*P*dr*cot(gama)^2 - 4*pi*dP*r*cot(gama)^2 + 8*pi*P*dgama*r*cot(gama)*(cot(gama)^2 + 1), dr/r0;...
%             2*pi*dgama*r^3*(cot(gama)^2 + 1) - 6*pi*dr*r^2*cot(gama), 2*pi*dP*r^3*(cot(gama)^2 + 1) - (r*((dL*(tan(gama)^2 + 1))/r - (L*dr*(tan(gama)^2 + 1))/r^2 + (2*L*dgama*tan(gama)*(tan(gama)^2 + 1))/r))/r0 - (L*dr*(tan(gama)^2 + 1))/(r*r0) + 6*pi*P*dr*r^2*(cot(gama)^2 + 1) - 4*pi*P*dgama*r^3*cot(gama)*(cot(gama)^2 + 1), (r*((dL*tan(gama))/r^2 + (L*dgama*(tan(gama)^2 + 1))/r^2 - (2*L*dr*tan(gama))/r^3))/r0 - ((dL*tan(gama))/r + (L*dgama*(tan(gama)^2 + 1))/r - (L*dr*tan(gama))/r^2)/r0 - 6*pi*dP*r^2*cot(gama) + (L*dr*tan(gama))/(r^2*r0) - 12*pi*P*dr*r*cot(gama) + 6*pi*P*dgama*r^2*(cot(gama)^2 + 1), - (r*((dgama*(tan(gama)^2 + 1))/r - (dr*tan(gama))/r^2))/r0 - (dr*tan(gama))/(r*r0);...
%             0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                        dgama*cos(gama),                                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                                                                                                                     0];
%    
%     dfdu = [1*0.5;...
%             0;...
%             0;...
%             0];
%         
%     df_ddxdt = [-1,                                                                                                                               0,                                                                                                           0,                                                                            0;...
%                 pi*r^2 - 2*pi*r^2*cot(gama)^2, 4*pi*P*r^2*cot(gama)*(cot(gama)^2 + 1), (L - L0)/r0 + 2*pi*P*r - 4*pi*P*r*cot(gama)^2, r/r0;...
%                 -2*pi*r^3*cot(gama), 2*pi*P*r^3*(cot(gama)^2 + 1) - (L*(tan(gama)^2 + 1))/r0, (L*tan(gama))/(r*r0) - ((L*tan(gama))/r - (L0*tan(gama0))/r0)/r0 - 6*pi*P*r^2*cot(gama), -tan(gama)/r0;...
%                 0,                                                                                                                       sin(gama),                                                                                                           0,                                                                cos(gama0)/L0]; 
         
%% Flipped the sign of first two terms in first equation (makes more sense, but doesn't match ICRA)
%     f = [-dP + 0.5*(u - P);...  % The constant in front of (u-P) is arbitrary
%          dL - pi*r^2*dP - 2*pi*P*r*dr + 2*pi*cot(gama)^2*r^2*dP + 4*pi*cot(gama)^2*P*r*dr - 4*pi*cot(gama)*P*r^2*dgama*(cot(gama)^2 + 1);...
%          (tan(gama)*L*dr)/r^2 - (L*(tan(gama)^2 + 1)*dgama)/r - (tan(gama)*dL)/r - 2*pi*cot(gama)*r^3*dP + 2*pi*P*r^3*dgama*(cot(gama)^2 + 1) - 6*pi*cot(gama)*P*r^2*dr;...
%          sin(gama)*dgama + (cos(gama0)*dL)/L0];
%     
%     dfdx = [-1*0.5,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0,                                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                                                                                                                     0;...
%             4*pi*dr*r*cot(gama)^2 - 2*pi*dr*r - 4*pi*dgama*r^2*cot(gama)*(cot(gama)^2 + 1), 4*pi*P*dgama*r^2*(cot(gama)^2 + 1)^2 - 4*pi*dP*r^2*cot(gama)*(cot(gama)^2 + 1) - 8*pi*P*dr*r*cot(gama)*(cot(gama)^2 + 1) + 8*pi*P*dgama*r^2*cot(gama)^2*(cot(gama)^2 + 1), 4*pi*P*dr*cot(gama)^2 - 2*pi*dP*r - 2*pi*P*dr + 4*pi*dP*r*cot(gama)^2 - 8*pi*P*dgama*r*cot(gama)*(cot(gama)^2 + 1), 0;...
%             2*pi*dgama*r^3*(cot(gama)^2 + 1) - 6*pi*dr*r^2*cot(gama), 2*pi*dP*r^3*(cot(gama)^2 + 1) - (dL*(tan(gama)^2 + 1))/r + (L*dr*(tan(gama)^2 + 1))/r^2 - (2*L*dgama*tan(gama)*(tan(gama)^2 + 1))/r + 6*pi*P*dr*r^2*(cot(gama)^2 + 1) - 4*pi*P*dgama*r^3*cot(gama)*(cot(gama)^2 + 1), (dL*tan(gama))/r^2 + (L*dgama*(tan(gama)^2 + 1))/r^2 - 6*pi*dP*r^2*cot(gama) - (2*L*dr*tan(gama))/r^3 - 12*pi*P*dr*r*cot(gama) + 6*pi*P*dgama*r^2*(cot(gama)^2 + 1), (dr*tan(gama))/r^2 - (dgama*(tan(gama)^2 + 1))/r;...
%             0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                        dgama*cos(gama),                                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                                                                                                                     0];
%    
%     dfdu = [1*0.5;...
%             0;...
%             0;...
%             0];
%         
%     df_ddxdt = [-1,                                                                                                                               0,                                                                                                           0,                                                                            0;...
%                 2*pi*r^2*cot(gama)^2 - pi*r^2, -4*pi*P*r^2*cot(gama)*(cot(gama)^2 + 1), 4*pi*P*r*cot(gama)^2 - 2*pi*P*r, 1;...
%                 -2*pi*r^3*cot(gama), 2*pi*P*r^3*(cot(gama)^2 + 1) - (L*(tan(gama)^2 + 1))/r, (L*tan(gama))/r^2 - 6*pi*P*r^2*cot(gama), -tan(gama)/r;...
%                 0,                                                                                                                       sin(gama),                                                                                                           0,                                                                cos(gama0)/L0]; 
         
%% Re-did signs of equations according to conventions in notebook (1/13/2017)
% f = [-dP + 0.5*(u - P);...  % The constant in front of (u-P) is arbitrary
%     pi*r^2*dP - dL + 2*pi*P*r*dr - 2*pi*cot(gama)^2*r^2*dP - 4*pi*cot(gama)^2*P*r*dr + 4*pi*cot(gama)*P*r^2*dgama*(cot(gama)^2 + 1);...
%     (tan(gama)*L*dr)/r^2 - (L*(tan(gama)^2 + 1)*dgama)/r - (tan(gama)*dL)/r + 2*pi*cot(gama)*r^3*dP - 2*pi*P*r^3*dgama*(cot(gama)^2 + 1) + 6*pi*cot(gama)*P*r^2*dr;...
%     sin(gama)*dgama + (cos(gama0)*dL)/L0];
% 
% dfdx = [0];     % not needed for ode15i
% dfdu = [0];     % not needed for ode15i
% df_ddxdt = [0]; % not needed for ode15i


%% Re-did signs again... may have been an error before (1/13/2017)
% f = [-dP + 0.5*(u - P);...  % The constant in front of (u-P) is arbitrary
%      pi*r^2*dP - dL + 2*pi*P*r*dr - 2*pi*cot(gama)^2*r^2*dP - 4*pi*cot(gama)^2*P*r*dr + 4*pi*cot(gama)*P*r^2*dgama*(cot(gama)^2 + 1);...
%      (tan(gama)*dL)/r + (L*(tan(gama)^2 + 1)*dgama)/r - (tan(gama)*L*dr)/r^2 + 2*pi*cot(gama)*r^3*dP - 2*pi*P*r^3*dgama*(cot(gama)^2 + 1) + 6*pi*cot(gama)*P*r^2*dr;...
%      sin(gama)*dgama + (cos(gama0)*dL)/L0];
% 
% dfdx = [0];     % not needed for ode15i
% dfdu = [0];     % not needed for ode15i
% df_ddxdt = [0]; % not needed for ode15i

%% F_elast = (r/r0 + 1)*(L0-L) * 1; M_elast = (r/r0 + 1)*(-1) * phi * 1 (1/13/2017)
% f = [-dP + 0.5*(u - P);...  % The constant in front of (u-P) is arbitrary
%      pi*r^2*dP - (r/r0 + 1)*dL + (dr*(L0 - L))/r0 + 2*pi*P*r*dr - 2*pi*cot(gama)^2*r^2*dP - 4*pi*cot(gama)^2*P*r*dr + 4*pi*cot(gama)*P*r^2*dgama*(cot(gama)^2 + 1);...
%      (r/r0 + 1)*((tan(gama)*dL)/r + (L*(tan(gama)^2 + 1)*dgama)/r - (tan(gama)*L*dr)/r^2) - (((L0*tan(gama0))/r0 - (tan(gama)*L)/r)*dr)/r0 + 2*pi*cot(gama)*r^3*dP - 2*pi*P*r^3*dgama*(cot(gama)^2 + 1) + 6*pi*cot(gama)*P*r^2*dr;...
%      sin(gama)*dgama + (cos(gama0)*dL)/L0];
% 
% dfdx = [0];     % not needed for ode15i
% dfdu = [0];     % not needed for ode15i
% df_ddxdt = [0]; % not needed for ode15i


%% Added constants to scale F_elast and M_elast (1/13/2017)
% f = [-dP + 0.5*(u - P);...  % The constant in front of (u-P) is arbitrary
%      pi*r^2*dP - c1*(r/r0 + 1)*dL + 2*pi*P*r*dr + (c1*dr*(L0 - L))/r0 - 2*pi*cot(gama)^2*r^2*dP - 4*pi*cot(gama)^2*P*r*dr + 4*pi*cot(gama)*P*r^2*dgama*(cot(gama)^2 + 1);...
%      c4*(r/r0 + 1)*((tan(gama)*dL)/r + (L*(tan(gama)^2 + 1)*dgama)/r - (tan(gama)*L*dr)/r^2) - (c4*((L0*tan(gama0))/r0 - (tan(gama)*L)/r)*dr)/r0 + 2*pi*cot(gama)*r^3*dP - 2*pi*P*r^3*dgama*(cot(gama)^2 + 1) + 6*pi*cot(gama)*P*r^2*dr;...
%      sin(gama)*dgama + (cos(gama0)*dL)/L0];
% 
% 
% dfdx = [0];     % not needed for ode15i
% dfdu = [0];     % not needed for ode15i
% df_ddxdt = [0]; % not needed for ode15i


%% F_elast = c1*(L0-L), M_elast = c4*(-1)*phi, with correct sign conventions (1/15/2017)
% f = [-dP + 0.5*(u - P);...  % The constant in front of (u-P) is arbitrary 
%      pi*r^2*dP - c1*dL + 2*pi*P*r*dr - 2*pi*cot(gama)^2*r^2*dP - 4*pi*cot(gama)^2*P*r*dr + 4*pi*cot(gama)*P*r^2*dgama*(cot(gama)^2 + 1);...
%      c4*((tan(gama)*dL)/r + (L*(tan(gama)^2 + 1)*dgama)/r - (tan(gama)*L*dr)/r^2) + 2*pi*cot(gama)*r^3*dP - 2*pi*P*r^3*dgama*(cot(gama)^2 + 1) + 6*pi*cot(gama)*P*r^2*dr;...
%      sin(gama)*dgama + (cos(gama0)*dL)/L0];
% 
% dfdx = [0];     % not needed for ode15i 
% dfdu = [0];     % not needed for ode15i
% df_ddxdt = [0]; % not needed for ode15i
 


%% 1/15/2017: F_elast = M_elast = 0, with correct sign conventions in place
% f = [-dP + 0.5*(u - P);...  % The constant in front of (u-P) is arbitrary 
%      pi*r^2*dP + 2*pi*P*r*dr - 2*pi*cot(gama)^2*r^2*dP - 4*pi*cot(gama)^2*P*r*dr + 4*pi*cot(gama)*P*r^2*dgama*(cot(gama)^2 + 1);...
%      2*pi*cot(gama)*r^3*dP - 2*pi*P*r^3*dgama*(cot(gama)^2 + 1) + 6*pi*cot(gama)*P*r^2*dr;...
%      sin(gama)*dgama + (cos(gama0)*dL)/L0];
%  
% dfdx = [0];     % not needed for ode15i
% dfdu = [0];     % not needed for ode15i
% df_ddxdt = [0]; % not needed for ode15i

%% Pressure dependence incorporated: F_elast = c1*(L0-L)*P, M_elast = c4*(-1)*phi*P (1/16/2017)
% f = [-dP + 0.5*(u - P);...  % The constant in front of (u-P) is arbitrary 
%      c1*dP*(L0 - L) - c1*P*dL + pi*r^2*dP + 2*pi*P*r*dr - 2*pi*cot(gama)^2*r^2*dP - 4*pi*cot(gama)^2*P*r*dr + 4*pi*cot(gama)*P*r^2*dgama*(cot(gama)^2 + 1);...
%      c4*P*((tan(gama)*dL)/r + (L*(tan(gama)^2 + 1)*dgama)/r - (tan(gama)*L*dr)/r^2) - c4*((L0*tan(gama0))/r0 - (tan(gama)*L)/r)*dP + 2*pi*cot(gama)*r^3*dP - 2*pi*P*r^3*dgama*(cot(gama)^2 + 1) + 6*pi*cot(gama)*P*r^2*dr;...
%      sin(gama)*dgama + (cos(gama0)*dL)/L0];
%  
% dfdx = [0];     % not needed for ode15i
% dfdu = [0];     % not needed for ode15i
% df_ddxdt = [0]; % not needed for ode15i

%% F_elast = c1*(L0-L), M_elast = c4*(-1)*phi,  3rd equation is 0 == -(r/r0)*(L/cos(gama)) + L0/cos(gama0)  (1/16/17)

% f = [-dP + 0.5*(u - P);...  % The constant in front of (u-P) is arbitrary 
%      pi*r^2*dP - c1*dL + 2*pi*P*r*dr - 2*pi*cot(gama)^2*r^2*dP - 4*pi*cot(gama)^2*P*r*dr + 4*pi*cot(gama)*P*r^2*dgama*(cot(gama)^2 + 1);...
%      c4*((tan(gama)*dL)/r + (L*(tan(gama)^2 + 1)*dgama)/r - (tan(gama)*L*dr)/r^2) + 2*pi*cot(gama)*r^3*dP - 2*pi*P*r^3*dgama*(cot(gama)^2 + 1) + 6*pi*cot(gama)*P*r^2*dr;...
%      - (L*dr)/(r0*cos(gama)) - (r*dL)/(r0*cos(gama)) - (sin(gama)*L*r*dgama)/(r0*cos(gama)^2)];
% 
% 
% dfdx = [0];     % not needed for ode15i 
% dfdu = [0];     % not needed for ode15i
% df_ddxdt = [0]; % not needed for ode15i


%% Trying to recreate correct results pre-ICRA:  Kf = (c1*r - c2)/L0; Kt = (c3*r + c4)/L0; F_elast = Kf*(L0-L); M_elast = Kt*phi; (1/16/2017)
f = [-dP + 0.5*(u - P);...  % The constant in front of (u-P) is arbitrary 
     ((c2 - c1*r)*dL)/L0 + pi*r^2*dP + 2*pi*P*r*dr - 2*pi*cot(gama)^2*r^2*dP + (c1*dr*(L0 - L))/L0 - 4*pi*cot(gama)^2*P*r*dr + 4*pi*cot(gama)*P*r^2*dgama*(cot(gama)^2 + 1);...
     (c3*((L0*tan(gama0))/r0 - (tan(gama)*L)/r)*dr)/L0 - ((c4 + c3*r)*((tan(gama)*dL)/r + (L*(tan(gama)^2 + 1)*dgama)/r - (tan(gama)*L*dr)/r^2))/L0 + 2*pi*cot(gama)*r^3*dP - 2*pi*P*r^3*dgama*(cot(gama)^2 + 1) + 6*pi*cot(gama)*P*r^2*dr;...
     sin(gama)*dgama + (cos(gama0)*dL)/L0];
 
dfdx = [0];     % not needed for ode15i 
dfdu = [0];     % not needed for ode15i
df_ddxdt = [0]; % not needed for ode15i

end

%% this is the phi constraint (only here as a reminder for when I make it a constraint later)
% -phi + (-tan(gama)*L/r + tan(gama0)*L0/r0)