function Fsym = Feval(in1,in2,t0,in4,u)
%FEVAL
%    FSYM = FEVAL(IN1,IN2,T0,IN4,U)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    21-Apr-2017 16:57:04

Fload = in4(:,1);
L = in1(:,4);
L0 = in2(:,4);
Mload = in4(:,2);
P = in1(:,1);
T = in1(:,6);
gama = in1(:,2);
gama0 = in2(:,2);
phi = in1(:,5);
r = in1(:,3);
r0 = in2(:,3);
t2 = cot(gama);
t3 = r.^2;
t4 = 1.0./L0;
t5 = r0.*t0.*2.0;
t6 = t0.^2;
t7 = t3+t5+t6;
t8 = sqrt(t7);
t9 = r-t8;
t10 = L-L0;
t11 = t4.*t10.*4.3105e3;
t12 = t11+1.029e2;
t13 = sin(gama);
t14 = r.*(1.0./2.0);
t15 = t8.*(1.0./2.0);
t16 = t14+t15;
t17 = t9.^2;
t18 = t17-r.*t9.*2.0;
t19 = cos(gama);
t20 = 1.0./r0;
t21 = tan(gama0);
Fsym = [T.*t13.*-2.0+P.*t2.*t3.*pi.*2.0+r.*t2.*t9.*t12.*t20.*pi.*(r-r0).*2.0;Fload-T.*t19.*2.0+P.*t3.*pi-t4.*t10.*t12.*t18.*pi;Mload+T.*t8.*t13.*2.0+t16.*t18.*pi.*atan((phi.*t16)./L).*(t4.*atan(phi.*r).*3.816858e2-1.367244e2);-P+u;L./t19+(r.*(phi-L0.*t20.*t21))./t13;-phi-(L.*tan(gama))./r+L0.*t20.*t21];
