function Fsym = Feval(in1,in2,t0,E,G,in6,u)
%FEVAL
%    FSYM = FEVAL(IN1,IN2,T0,E,G,IN6,U)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    18-Apr-2017 17:40:16

Fload = in6(:,1);
L = in1(:,4);
L0 = in2(:,4);
Mload = in6(:,2);
P = in1(:,1);
T = in1(:,6);
gama = in1(:,2);
gama0 = in2(:,2);
phi = in1(:,5);
r = in1(:,3);
r0 = in2(:,3);
t2 = cot(gama);
t3 = r.^2;
t4 = r0.*t0.*2.0;
t5 = t0.^2;
t6 = t3+t4+t5;
t7 = sqrt(t6);
t8 = r-t7;
t9 = sin(gama);
t10 = t8.^2;
t11 = t10-r.*t8.*2.0;
t12 = cos(gama);
t13 = 1.0./r0;
t14 = tan(gama0);
Fsym = [T.*t9.*-2.0+P.*t2.*t3.*pi.*2.0+E.*r.*t2.*t8.*t13.*pi.*(r-r0).*2.0;Fload-T.*t12.*2.0+P.*t3.*pi-(E.*t11.*pi.*(L-L0))./L0;Mload+T.*t7.*t9.*2.0-G.*t11.*pi.*atan((phi.*r)./L).*(r.*(1.0./2.0)+t7.*(1.0./2.0));-P+u;L./t12+(r.*(phi-L0.*t13.*t14))./t9;-phi-(L.*tan(gama))./r+L0.*t13.*t14];
