% kmpc_setup.m
%
% Creates an instance of the kmpc class based on user arguments.
% Must have a sysid class in the workspace for this to work

% define the projection matrix from lifted state to reference trajectory
Cref = ksysid.model.C;

kmpc = kmpc( ksysid ,...
        'horizon' , 3 ,...
        'input_bounds' , [ 0 , 10 ],... 
        'input_slopeConst' , [0.5e-2],... 
        'input_smoothConst' , [1e-1],... 
        'state_bounds' , [] ,...
        'cost_running' , 0.1 ,...
        'cost_terminal' , 100 ,...
        'cost_input' , 0 ,...
        'projmtx' , Cref ); 