function dlift = jacobianLift(in1)
%JACOBIANLIFT
%    DLIFT = JACOBIANLIFT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    01-Apr-2019 17:53:52

dlift = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0],[4,3]);
