function polyBasis = stateLift(in1)
%STATELIFT
%    POLYBASIS = STATELIFT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Mar-2019 13:11:42

x1 = in1(1,:);
x2 = in1(2,:);
polyBasis = [x1.*2.0;x2.*2.0;x1.^2.*4.0-2.0;x1.*x2.*4.0;x2.^2.*4.0-2.0;1.0];
