function polyBasis = stateLift(in1)
%STATELIFT
%    POLYBASIS = STATELIFT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    16-Apr-2019 14:48:33

x1 = in1(1,:);
x2 = in1(2,:);
polyBasis = [x1;x2;x1.^2;x1.*x2;x2.^2;1.0];
