function polyBasis = stateLift(in1)
%STATELIFT
%    POLYBASIS = STATELIFT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    16-Apr-2019 14:46:03

ud1 = in1(5,:);
x1 = in1(1,:);
x2 = in1(2,:);
xd1 = in1(3,:);
xd2 = in1(4,:);
polyBasis = [x1;x2;xd1;xd2;ud1;x1.^2;x1.*x2;x2.^2;x1.*xd1;x2.*xd1;xd1.^2;x1.*xd2;x2.*xd2;xd1.*xd2;xd2.^2;ud1.*x1;ud1.*x2;ud1.*xd1;ud1.*xd2;ud1.^2;1.0];
