function polyBasis = stateLift(in1,w1)
%STATELIFT
%    POLYBASIS = STATELIFT(IN1,W1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    22-Apr-2019 13:27:51

x1 = in1(1,:);
x2 = in1(2,:);
t2 = x1.^2;
t3 = x2.^2;
polyBasis = [x1;x2;t2;x1.*x2;t3;1.0;w1.*x1;w1.*x2;t2.*w1;w1.*x1.*x2;t3.*w1;w1];
