function fourierBasis = fourierLift(x1,u1)
%FOURIERLIFT
%    FOURIERBASIS = FOURIERLIFT(X1,U1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    10-Oct-2018 14:44:09

t2 = u1.*pi.*2.0;
t3 = cos(t2);
t4 = x1.*pi.*2.0;
t5 = cos(t4);
t6 = sin(t2);
t7 = sin(t4);
fourierBasis = [1.0;t3;t6;t5;t3.*t5;t5.*t6;t7;t3.*t7;t6.*t7];
