function dlift = jacobianLift(x1,u1)
%JACOBIANLIFT
%    DLIFT = JACOBIANLIFT(X1,U1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    17-Oct-2018 15:15:27

dlift = [0.0;1.0;0.0];
