function dlift = jacobianLift(in1,u1)
%JACOBIANLIFT
%    DLIFT = JACOBIANLIFT(IN1,U1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    17-Oct-2018 19:25:08

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
dlift = reshape([0.0,1.0,0.0,0.0,0.0,x1.*2.0,x2,0.0,x3,0.0,0.0,u1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,x1,x2.*2.0,0.0,x3,0.0,0.0,u1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,x1,x2,x3.*2.0,0.0,0.0,u1,0.0],[15,3]);
