function dlift = jacobianLift(in1,u1)
%JACOBIANLIFT
%    DLIFT = JACOBIANLIFT(IN1,U1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    17-Oct-2018 13:55:58

dlift = reshape([0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0],[5,3]);
