function vf2 = vf_koopman(x1,u1)
%VF_KOOPMAN
%    VF2 = VF_KOOPMAN(X1,U1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    17-Oct-2018 15:15:29

vf2 = u1.*(-1.339014565705081)-x1.*3.251253561201231+3.913498350659982e-1;
