function vf = vf_real(in1)
%VF_REAL
%    VF = VF_REAL(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    01-Aug-2018 10:25:56

x1 = in1(1,:);
x2 = in1(2,:);
vf = [x2;-x1-x2.*(x1.^2-1.0)];
