function J_ki = J_ki(in1,in2,L_k)
%J_KI
%    J_KI = J_KI(IN1,IN2,L_K)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    15-Nov-2017 16:23:22

a_ki = in2(:,1);
b_ki = in2(:,2);
phi_k = in1(3,:);
psi_k = in1(1,:);
theta_k = in1(2,:);
t2 = cos(theta_k);
t4 = sin(theta_k);
t5 = a_ki.*t4;
t6 = sin(psi_k);
t7 = b_ki.*t2.*t6;
t3 = L_k-t5+t7;
t8 = phi_k.^2;
t9 = a_ki.^2;
t10 = b_ki.^2;
t11 = t9+t10;
t12 = t8.*t11;
t13 = t3.^2;
t14 = t12+t13;
t15 = 1.0./sqrt(t14);
J_ki = reshape([b_ki.*t2.*t3.*t15.*cos(psi_k),0.0,-t3.*t15.*(a_ki.*t2+b_ki.*t4.*t6),0.0,phi_k.*t11.*t15,1.0],[2,3]);
