function Jorient2pos = Jorient2pos(in1,L_)
%JORIENT2POS
%    JORIENT2POS = JORIENT2POS(IN1,L_)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    09-Jan-2018 13:09:08

phi_ = in1(3,:);
psi_ = in1(1,:);
theta_ = in1(2,:);
Jorient2pos = reshape([L_.*(cos(psi_).*sin(phi_)-cos(phi_).*sin(psi_).*sin(theta_)).*(1.0./2.0),L_.*(cos(phi_).*cos(psi_)+sin(phi_).*sin(psi_).*sin(theta_)).*(-1.0./2.0),L_.*cos(theta_).*sin(psi_).*(-1.0./2.0),L_.*cos(phi_).*cos(psi_).*cos(theta_).*(1.0./2.0),L_.*cos(psi_).*cos(theta_).*sin(phi_).*(1.0./2.0),L_.*cos(psi_).*sin(theta_).*(-1.0./2.0),L_.*(cos(phi_).*sin(psi_)-cos(psi_).*sin(phi_).*sin(theta_)).*(1.0./2.0),L_.*(sin(phi_).*sin(psi_)+cos(phi_).*cos(psi_).*sin(theta_)).*(1.0./2.0),0.0],[3,3]);
