function Jx = Jx(in1)
%JX
%    JX = JX(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    13-Nov-2017 15:16:18

x04 = in1(4,:);
x05 = in1(5,:);
x06 = in1(6,:);
Jx = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,cos(x04).*sin(x06).*(1.0./2.0e1)-cos(x06).*sin(x04).*sin(x05).*(1.0./2.0e1),cos(x04).*cos(x06).*(-1.0./2.0e1)-sin(x04).*sin(x05).*sin(x06).*(1.0./2.0e1),cos(x05).*sin(x04).*(-1.0./2.0e1),1.0,0.0,0.0,cos(x04).*cos(x05).*cos(x06).*(1.0./2.0e1),cos(x04).*cos(x05).*sin(x06).*(1.0./2.0e1),cos(x04).*sin(x05).*(-1.0./2.0e1),0.0,1.0,0.0,cos(x06).*sin(x04).*(1.0./2.0e1)-cos(x04).*sin(x05).*sin(x06).*(1.0./2.0e1),sin(x04).*sin(x06).*(1.0./2.0e1)+cos(x04).*cos(x06).*sin(x05).*(1.0./2.0e1),0.0,0.0,0.0,1.0],[6,6]);
