function Jx = Jx(in1)
%JX
%    JX = JX(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    12-Nov-2017 19:05:13

Jx = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[6,6]);
