function Jx = Jx(in1)
%JX
%    JX = JX(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    15-Nov-2017 16:23:22

Jx = reshape([1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0],[3,3]);
