function f = calcFelast( x, params )
%calcFelast - Evaluates the elastomer force at a specific point x. 
%   Must run getFelast_... prior to calling this funcion

felast = params.felast;

f = [felast.x1.PolynomialExpression(x(1), x(2), x(3), x(4), x(5), x(6)) ;...
     felast.x2.PolynomialExpression(x(1), x(2), x(3), x(4), x(5), x(6)) ;...
     felast.x3.PolynomialExpression(x(1), x(2), x(3), x(4), x(5), x(6)) ;...
     felast.x4.PolynomialExpression(x(1), x(2), x(3), x(4), x(5), x(6)) ;...
     felast.x5.PolynomialExpression(x(1), x(2), x(3), x(4), x(5), x(6)) ;...
     felast.x6.PolynomialExpression(x(1), x(2), x(3), x(4), x(5), x(6)) ;...
    ];

end

