function q = x2q(in1)
%X2Q
%    Q = X2Q(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    20-Apr-2018 10:29:22

x3 = in1(3,:);
x4 = in1(4,:);
q = [x3;x4;x3;x4;x3;x4];
