function q = x2q(in1)
%X2Q
%    Q = X2Q(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    15-Mar-2018 17:27:31

x3 = in1(3,:);
x6 = in1(6,:);
t2 = x3-1.0./1.0e1;
q = [t2;x6;t2;x6;t2;x6];
