function q = x2q(in1)
%X2Q
%    Q = X2Q(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    13-Mar-2018 15:19:52

x3 = in1(3,:);
x6 = in1(6,:);
q = [x3;x6;x3;x6;x3;x6];
