function xcoupled = xind2xcoupled(in1)
%XIND2XCOUPLED
%    XCOUPLED = XIND2XCOUPLED(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    17-Apr-2018 12:20:18

xind1 = in1(1,:);
xind2 = in1(2,:);
xcoupled = [0.0,0.0,xind1,xind2,0.0,0.0];
