function xcoupled = xind2xcoupled(in1)
%XIND2XCOUPLED
%    XCOUPLED = XIND2XCOUPLED(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    19-Mar-2018 10:54:59

xind1 = in1(1,:);
xind2 = in1(2,:);
xind3 = in1(3,:);
t2 = cos(xind1);
t3 = sin(xind3);
t4 = cos(xind3);
t5 = sin(xind1);
t6 = sin(xind2);
xcoupled = [t3.*t5.*(1.0./2.0e1)+t2.*t4.*t6.*(1.0./2.0e1),t2.*t3.*(-1.0./2.0e1)+t4.*t5.*t6.*(1.0./2.0e1),t4.*cos(xind2).*(1.0./2.0e1)-1.0./2.0e1,xind1,xind2,xind3];
