function xdot = arm_1000s_load10_dynamics(in1,u1)
%ARM_1000S_LOAD10_DYNAMICS
%    XDOT = ARM_1000S_LOAD10_DYNAMICS(IN1,U1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    11-Mar-2019 16:37:29

x1 = in1(1,:);
x2 = in1(2,:);
xdot = [x2;u1.*(6.0e1./3.1e1)-x1.*(6.0e1./3.1e1)-x2.*(3.0e1./3.1e1)+cos(x1).*9.493548387096774];
