function input = get_input(in1,in2)
%GET_INPUT
%    INPUT = GET_INPUT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    24-Jul-2019 17:17:37

alpha1 = in1(1,:);
alpha2 = in1(2,:);
alpha3 = in1(3,:);
alpha4 = in1(4,:);
alpha5 = in1(5,:);
alpha6 = in1(6,:);
u1 = in2(1,:);
u2 = in2(2,:);
input = [alpha1./1.0e+3-u1./1.0e+3;alpha2./1.0e+3-u1./1.0e+3;alpha3./1.0e+3-u1./1.0e+3;alpha4./1.0e+3-u2./1.0e+3;alpha5./1.0e+3-u2./1.0e+3;alpha6./1.0e+3-u2./1.0e+3];
