function damp = get_damp(in1)
%GET_DAMP
%    DAMP = GET_DAMP(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    24-Jul-2019 17:17:37

alphadot1 = in1(1,:);
alphadot2 = in1(2,:);
alphadot3 = in1(3,:);
alphadot4 = in1(4,:);
alphadot5 = in1(5,:);
alphadot6 = in1(6,:);
damp = [alphadot1./1.0e+4;alphadot2./1.0e+4;alphadot3./1.0e+4;alphadot4./1.0e+4;alphadot5./1.0e+4;alphadot6./1.0e+4];
