function dampNinput = get_dampNinput(in1,in2,in3)
%GET_DAMPNINPUT
%    DAMPNINPUT = GET_DAMPNINPUT(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    24-Jul-2019 17:17:37

alpha1 = in1(1,:);
alpha2 = in1(2,:);
alpha3 = in1(3,:);
alpha4 = in1(4,:);
alpha5 = in1(5,:);
alpha6 = in1(6,:);
alphadot1 = in2(1,:);
alphadot2 = in2(2,:);
alphadot3 = in2(3,:);
alphadot4 = in2(4,:);
alphadot5 = in2(5,:);
alphadot6 = in2(6,:);
u1 = in3(1,:);
u2 = in3(2,:);
dampNinput = [alpha1./1.0e+3+alphadot1./1.0e+4-u1./1.0e+3;alpha2./1.0e+3+alphadot2./1.0e+4-u1./1.0e+3;alpha3./1.0e+3+alphadot3./1.0e+4-u1./1.0e+3;alpha4./1.0e+3+alphadot4./1.0e+4-u2./1.0e+3;alpha5./1.0e+3+alphadot5./1.0e+4-u2./1.0e+3;alpha6./1.0e+3+alphadot6./1.0e+4-u2./1.0e+3];
