function J_aq = J_aq(in1)
%J_AQ
%    J_AQ = J_AQ(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    20-Jul-2019 12:53:06

alpha1 = in1(1,:);
alpha2 = in1(2,:);
alpha3 = in1(3,:);
t2 = alpha1.^2;
t3 = alpha2.^2;
t4 = alpha3.^2;
t5 = t2./2.0e+2;
t6 = t3./2.0e+2;
t7 = t4./4.0e+2;
J_aq = reshape([-t5-1.0./5.0e+1,t5+1.0./5.0e+1,-t6-1.0./5.0e+1,t6+1.0./5.0e+1,-t7-1.0./1.0e+2,t7+1.0./1.0e+2],[2,3]);
