function J_aq = J_aq(in1)
%J_AQ
%    J_AQ = J_AQ(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    20-Nov-2017 21:07:17

alpha1 = in1(1,:);
alpha2 = in1(2,:);
alpha3 = in1(3,:);
alpha4 = in1(4,:);
alpha5 = in1(5,:);
alpha6 = in1(6,:);
t2 = alpha1.^2;
t3 = alpha2.^2;
t4 = alpha3.^2;
t5 = alpha4.^2;
t6 = alpha5.^2;
t7 = alpha6.^2;
J_aq = reshape([t2.*(-1.0./2.0e2)-1.0./5.0e1,t2.*(1.0./2.0e2)+1.0./5.0e1,t3.*(-1.0./2.0e2)-1.0./5.0e1,t3.*(1.0./2.0e2)+1.0./5.0e1,t4.*(-1.0./2.0e2)-1.0./5.0e1,t4.*(1.0./2.0e2)+1.0./5.0e1,t5.*(-1.0./2.0e2)-1.0./5.0e1,t5.*(1.0./2.0e2)+1.0./5.0e1,t6.*(-1.0./2.0e2)-1.0./5.0e1,t6.*(1.0./2.0e2)+1.0./5.0e1,t7.*(-1.0./4.0e2)-1.0./1.0e2,t7.*(1.0./4.0e2)+1.0./1.0e2],[2,6]);
