function J_ax = J_ax(in1)
%J_AX
%    J_AX = J_AX(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    20-Jul-2019 12:53:06

alpha2 = in1(2,:);
alpha3 = in1(3,:);
t2 = cos(alpha2);
t3 = sin(alpha2);
t4 = alpha2+alpha3;
t5 = cos(t4);
t6 = sin(t4);
t7 = t2./1.0e+1;
t8 = t3./1.0e+1;
t9 = -t8;
t10 = t5./1.0e+1;
t11 = t6./1.0e+1;
t12 = -t11;
J_ax = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t7,t9,1.0,t7+t10,t9+t12,1.0,0.0,0.0,0.0,0.0,0.0,0.0,t10,t12,1.0],[9,3]);
