function dYdt = Pendulum_sys(t,Y,m,g,l)
%PENDULUM_SYS
%    DYDT = PENDULUM_SYS(T,Y,M,G,L)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    19-Oct-2016 14:05:53

dYdt = [Y(2);-(g.*sin(Y(1)))./l];
