function polyBasis = polyLift(in1,u1)
%POLYLIFT
%    POLYBASIS = POLYLIFT(IN1,U1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    03-Aug-2018 13:19:33

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
polyBasis = [1.0;x1;x2;x3;x4;u1;x1.^2;x1.*x2;x2.^2;x1.*x3;x2.*x3;x3.^2;x1.*x4;x2.*x4;x3.*x4;x4.^2;u1.*x1;u1.*x2;u1.*x3;u1.*x4;u1.^2];
