function polyBasis = polyLift(in1,u1)
%POLYLIFT
%    POLYBASIS = POLYLIFT(IN1,U1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    02-Aug-2018 18:40:49

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
polyBasis = [1.0;x1;x2;x3;x4;u1];
