function fourierBasis = fourierLift(in1,u1)
%FOURIERLIFT
%    FOURIERBASIS = FOURIERLIFT(IN1,U1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Sep-2018 17:45:31

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
t2 = u1.*pi.*2.0;
t3 = cos(t2);
t4 = x3.*pi.*2.0;
t5 = cos(t4);
t6 = sin(t2);
t7 = sin(t4);
t8 = x2.*pi.*2.0;
t9 = cos(t8);
t10 = sin(t8);
t11 = x1.*pi.*2.0;
t12 = cos(t11);
t13 = sin(t11);
fourierBasis = [1.0;t3;t6;t5;t3.*t5;t5.*t6;t7;t3.*t7;t6.*t7;t9;t3.*t9;t6.*t9;t5.*t9;t3.*t5.*t9;t5.*t6.*t9;t7.*t9;t3.*t7.*t9;t6.*t7.*t9;t10;t3.*t10;t6.*t10;t5.*t10;t3.*t5.*t10;t5.*t6.*t10;t7.*t10;t3.*t7.*t10;t6.*t7.*t10;t12;t3.*t12;t6.*t12;t5.*t12;t3.*t5.*t12;t5.*t6.*t12;t7.*t12;t3.*t7.*t12;t6.*t7.*t12;t9.*t12;t3.*t9.*t12;t6.*t9.*t12;t5.*t9.*t12;t3.*t5.*t9.*t12;t5.*t6.*t9.*t12;t7.*t9.*t12;t3.*t7.*t9.*t12;t6.*t7.*t9.*t12;t10.*t12;t3.*t10.*t12;t6.*t10.*t12;t5.*t10.*t12;t3.*t5.*t10.*t12;t5.*t6.*t10.*t12;t7.*t10.*t12;t3.*t7.*t10.*t12;t6.*t7.*t10.*t12;t13;t3.*t13;t6.*t13;t5.*t13;t3.*t5.*t13;t5.*t6.*t13;t7.*t13;t3.*t7.*t13;t6.*t7.*t13;t9.*t13;t3.*t9.*t13;t6.*t9.*t13;t5.*t9.*t13;t3.*t5.*t9.*t13;t5.*t6.*t9.*t13;t7.*t9.*t13;t3.*t7.*t9.*t13;t6.*t7.*t9.*t13;t10.*t13;t3.*t10.*t13;t6.*t10.*t13;t5.*t10.*t13;t3.*t5.*t10.*t13;t5.*t6.*t10.*t13;t7.*t10.*t13;t3.*t7.*t10.*t13;t6.*t7.*t10.*t13];
