function fourierBasis = fourierLift(x1,u1)
%FOURIERLIFT
%    FOURIERBASIS = FOURIERLIFT(X1,U1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    16-Oct-2018 19:39:54

t2 = u1.*pi.*2.0;
t3 = sin(t2);
t4 = x1.*pi.*2.0;
t5 = sin(t4);
t6 = u1.*pi.*4.0;
t7 = sin(t6);
t8 = u1.*pi.*6.0;
t9 = sin(t8);
t10 = u1.*pi.*8.0;
t11 = sin(t10);
t12 = x1.*pi.*4.0;
t13 = sin(t12);
t14 = x1.*pi.*6.0;
t15 = sin(t14);
t16 = x1.*pi.*8.0;
t17 = sin(t16);
fourierBasis = [1.0;t3;t7;t9;t11;t5;t3.*t5;t5.*t7;t5.*t9;t5.*t11;t13;t3.*t13;t7.*t13;t9.*t13;t11.*t13;t15;t3.*t15;t7.*t15;t9.*t15;t11.*t15;t17;t3.*t17;t7.*t17;t9.*t17;t11.*t17];
