function dlift = jacobianLift(x1,u1)
%JACOBIANLIFT
%    DLIFT = JACOBIANLIFT(X1,U1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    16-Oct-2018 19:39:54

t2 = x1.*pi.*2.0;
t3 = cos(t2);
t4 = x1.*pi.*4.0;
t5 = cos(t4);
t6 = u1.*pi.*2.0;
t7 = sin(t6);
t8 = u1.*pi.*4.0;
t9 = sin(t8);
t10 = u1.*pi.*6.0;
t11 = sin(t10);
t12 = u1.*pi.*8.0;
t13 = sin(t12);
t14 = x1.*pi.*6.0;
t15 = cos(t14);
t16 = x1.*pi.*8.0;
t17 = cos(t16);
dlift = [0.0;0.0;0.0;0.0;0.0;t3.*pi.*2.0;t3.*t7.*pi.*2.0;t3.*t9.*pi.*2.0;t3.*t11.*pi.*2.0;t3.*t13.*pi.*2.0;t5.*pi.*4.0;t5.*t7.*pi.*4.0;t5.*t9.*pi.*4.0;t5.*t11.*pi.*4.0;t5.*t13.*pi.*4.0;t15.*pi.*6.0;t7.*t15.*pi.*6.0;t9.*t15.*pi.*6.0;t11.*t15.*pi.*6.0;t13.*t15.*pi.*6.0;t17.*pi.*8.0;t7.*t17.*pi.*8.0;t9.*t17.*pi.*8.0;t11.*t17.*pi.*8.0;t13.*t17.*pi.*8.0];
