function polyBasis = polyLift(in1,u1)
%POLYLIFT
%    POLYBASIS = POLYLIFT(IN1,U1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    10-Oct-2018 13:30:05

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
polyBasis = [1.0;x1;x2;x3;u1;x1.^2;x1.*x2;x2.^2;x1.*x3;x2.*x3;x3.^2;u1.*x1;u1.*x2;u1.*x3;u1.^2];
