function vf = vf_real(in1,u1)
%VF_REAL
%    VF = VF_REAL(IN1,U1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    13-Jul-2018 17:42:18

x1 = in1(1,:);
x2 = in1(2,:);
t2 = x1.^2;
vf = [x2;x1-x2.*(1.0./5.0)+t2.*u1.*(1.0./5.0)-t2.*x1];
