function p = polyLift(in1)
%POLYLIFT
%    P = POLYLIFT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    12-Jul-2018 17:36:20

x1 = in1(1,:);
x2 = in1(2,:);
t2 = x1.^2;
t3 = x2.^2;
p = [1.0;x1;x2;t2;x1.*x2;t3;t2.*x1;t2.*x2;t3.*x1;t3.*x2];
