function sinBasis = sinLift(in1,in2)
%SINLIFT
%    SINBASIS = SINLIFT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    06-Aug-2018 18:34:56

x1 = in1(1,:);
x2 = in1(2,:);
sinBasis = [1.0;cos(pi.*(x1.*(1.0./1.0e2)+1.0./2.0).*2.0);cos(pi.*(x2.*(1.0./1.0e2)+1.0./2.0).*2.0)];
