function sinBasis = sinLift(in1,u1)
%SINLIFT
%    SINBASIS = SINLIFT(IN1,U1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    06-Aug-2018 14:27:31

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
sinBasis = [1.0;cos(pi.*(x1.*(1.0./1.0e2)+1.0./2.0).*2.0);cos(pi.*(x2.*(1.0./1.0e2)+1.0./2.0).*2.0);cos(pi.*(x3.*(1.0./1.0e2)+1.0./2.0).*2.0);cos(pi.*(x4.*(1.0./1.0e2)+1.0./2.0).*2.0);cos(pi.*(u1.*(1.0./1.0e2)+1.0./2.0).*2.0)];
