function trigBasis = trigLift(in1,in2)
%TRIGLIFT
%    TRIGBASIS = TRIGLIFT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    06-Aug-2018 18:44:11

x1 = in1(1,:);
x2 = in1(2,:);
t2 = cos(x2);
t3 = sin(x2);
t4 = sin(x1);
t5 = cos(x1);
trigBasis = [1.0;t3;t2;t2.*t3;t4;t3.*t4;t2.*t4;t2.*t3.*t4;t5;t3.*t5;t2.*t5;t2.*t3.*t5;t4.*t5;t3.*t4.*t5;t2.*t4.*t5;t2.*t3.*t4.*t5];
