function xdot = SMD_100s_dynamics(in1,u1)
%SMD_100S_DYNAMICS
%    XDOT = SMD_100S_DYNAMICS(IN1,U1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    29-Mar-2019 12:57:22

x1 = in1(1,:);
x2 = in1(2,:);
xdot = [x2;u1-x1-x2];
