function polyBasis = stateLift(in1)
%STATELIFT
%    POLYBASIS = STATELIFT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    02-Apr-2019 17:15:04

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
t2 = x1.^2;
t3 = x2.^2;
t4 = x3.^2;
polyBasis = [x1;x2;x3;t2;x1.*x2;t3;x1.*x3;x2.*x3;t4;t2.*x1;t2.*x2;t3.*x1;t3.*x2;t2.*x3;x1.*x2.*x3;t3.*x3;t4.*x1;t4.*x2;t4.*x3;1.0];
